# This file was generated by GoReleaser. DO NOT EDIT.
cask "anchors" do
  version "0.1.300"

  on_macos do
    on_arm do
      sha256 "2f6d098246b1b6a9089bc2f08c4cc0fbbe5d0383454e573bec9c766b1b995fdc"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a57cc43987bb1f850f4fd8c2ef814892b0aaaa5c572b85efa920731dc3fafc7"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fb2e65f6bbc1ccbfa544f526d8682b8fc76e65892d026f4825394b41f268ef4c"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "99983fecc0818b02eb4d8055f1f4413af041eabb28f76d426e0c62ac3296f3b2"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_linux_amd64.tar.gz"
    end
  end

  name "anchors"
  desc "Anchors — framework spec-first de continuidade para desenvolvimento assistido por IA"
  homepage "https://anchors.co2lab.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anchors"

  # No zap stanza required
end
