# This file was generated by GoReleaser. DO NOT EDIT.
cask "anchors" do
  version "0.1.235"

  on_macos do
    on_arm do
      sha256 "e28b50d53aa8eba3a64d3499f68656a33c956b32ce3b450dc37b90b59435e937"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb596b0d3d2956e30a6ef47edee191d36c1ed4f4dd1b914fa2a3e5dcca41a526"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ef1ab08f00e205524e7bf8c2e7289d4beaa3d8b92fc176779d706c07d6e7536f"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8349bb071e16f1d0e923fbfde743a8c62ebbbc7e857d8175508c6320913d5725"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_linux_amd64.tar.gz"
    end
  end

  name "anchors"
  desc "Anchors — framework spec-first de continuidade para desenvolvimento assistido por IA"
  homepage "https://anchors.co2lab.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anchors"

  # No zap stanza required
end
