# This file was generated by GoReleaser. DO NOT EDIT.
cask "anchors" do
  version "0.1.152"

  on_macos do
    on_arm do
      sha256 "d71be02339750e8bc6cdae93c6ec98698ecf01dd830601cf3787b62a9dd0a08e"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "15a6a2f57ad531341106b20f9f0fd895396c75ddcb5ba25d017c67c03ba97d7f"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4a994f67c4a2c5eeb77aa0524bb51b40e384499e6f8b1e9352d2387895f46e5f"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f145814aa768fe6200f66fe6d543481dcf7afcdbf0111005ac9542a2c17097e8"
      url "https://github.com/co2-lab/anchors/releases/download/v#{version}/anchors_#{version}_linux_amd64.tar.gz"
    end
  end

  name "anchors"
  desc "Anchors — framework spec-first de continuidade para desenvolvimento assistido por IA"
  homepage "https://anchors.co2lab.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anchors"

  # No zap stanza required
end
